#----------------------------------------------------------------
# AppVeyor configuration for R packages
#
# REFERENCES:
# * AppVeyor CI: https://ci.appveyor.com/
# * r-appveyor: https://github.com/krlmlr/r-appveyor
#
# Validate your .appveyor.yml file at
# https://ci.appveyor.com/tools/validate-yaml
#----------------------------------------------------------------

# Script from https://github.com/hadley/devtools/blob/master/appveyor.yml
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap

environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: false
    USE_RTOOLS: true
    PKGTYPE: both

  matrix:
    - R_VERSION: devel
      R_ARCH: x64
      GCC_PATH: mingw_64
      BIOC_USE_DEVEL: TRUE

    - R_VERSION: devel
      GCC_PATH: mingw_32
      BIOC_USE_DEVEL: TRUE

    - R_VERSION: release
      R_ARCH: x64
      GCC_PATH: mingw_64
      BIOC_USE_DEVEL: FALSE 

    - R_VERSION: release
      GCC_PATH: mingw_32
      BIOC_USE_DEVEL: FALSE 

    - R_VERSION: oldrel
      R_ARCH: x64
      GCC_PATH: mingw_64
      BIOC_USE_DEVEL: FALSE 

    - R_VERSION: oldrel
      GCC_PATH: mingw_32
      BIOC_USE_DEVEL: FALSE 

# Adapt as necessary starting from here
build_script:
  - echo Current directory=%CD%
  - travis-tool.sh github_package r-lib/covr Bioconductor/BiocManager
  - travis-tool.sh install_r testthat knitr
  - travis-tool.sh install_bioc BiocVersion BiocStyle
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_success:
  - Rscript -e 'covr::codecov()'

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: all-Rout.zip
    name: AllRout

cache:
  - C:\RLibrary -> appveyor.yml

